import { FaCloud, FaCode, FaDatabase, FaLayerGroup, FaTerminal } from 'react-icons/fa'
import { FaBolt, FaBoxesStacked, FaBuilding, FaDiagramProject, FaUserShield } from 'react-icons/fa6'
import {
  SiAngular,
  SiApachemaven,
  SiC,
  SiCss,
  SiDeno,
  SiDocker,
  SiDotnet,
  SiExpress,
  SiFramer,
  SiGooglecloud,
  SiGithubactions,
  SiGit,
  SiGithub,
  SiGnubash,
  SiHono,
  SiHtml5,
  SiIntellijidea,
  SiJavascript,
  SiJunit5,
  SiMongodb,
  SiMysql,
  SiRabbitmq,
  SiRaspberrypi,
  SiRedis,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNpm,
  SiOpenapiinitiative,
  SiOpenjdk,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiR,
  SiRazorpay,
  SiReact,
  SiRstudioide,
  SiRust,
  SiSass,
  SiSpringboot,
  SiSpring,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVscodium,
} from 'react-icons/si'
import { TbBrandCSharp, TbBrandVisualStudio, TbBrandVscode, TbMathFunction, TbSql } from 'react-icons/tb'

import type { CapabilityCategory } from './types'

export const capabilityCategories: CapabilityCategory[] = [
  {
    id: 'core-programming',
    title: 'Core Programming',
    icon: FaCode,
    skillRows: [
      [
        { id: 'typescript', label: 'TypeScript', icon: SiTypescript },
        { id: 'javascript', label: 'JavaScript', icon: SiJavascript },
        { id: 'java', label: 'Java', icon: SiOpenjdk },
        { id: 'csharp', label: 'C#', icon: TbBrandCSharp },
        { id: 'rust', label: 'Rust', icon: SiRust },
        { id: 'python', label: 'Python', icon: SiPython },
        { id: 'c', label: 'C', icon: SiC },
        { id: 'shell-script', label: 'Shell Script', icon: SiGnubash },
        { id: 'z-shell', label: 'Z Shell', icon: FaTerminal },
        { id: 'r', label: 'R', icon: SiR },
      ],
    ],
  },
  {
    id: 'engineering-paradigms',
    title: 'Engineering Paradigms',
    icon: FaLayerGroup,
    skillRows: [
      [
        { id: 'dsa', label: 'Data Structures & Algorithms', icon: FaBolt },
        { id: 'oops', label: 'OOPS', icon: FaBoxesStacked },
        { id: 'rest-architecture', label: 'REST Architecture', icon: SiOpenapiinitiative },
        { id: 'rbac', label: 'RBAC', icon: FaLayerGroup },
        { id: 'jwt', label: 'JWT', icon: FaUserShield },
        { id: 'oauth2', label: 'OAuth2', icon: FaUserShield },
        { id: 'layered-architecture', label: 'Layered Architecture', icon: FaLayerGroup },
        { id: 'microservices', label: 'Microservices', icon: FaDiagramProject },
        { id: 'monolithic', label: 'Monolithic Architecture', icon: FaBuilding },
      ],
    ],
  },
  {
    id: 'backend-runtime-systems',
    title: 'Backend & Runtime Systems',
    icon: SiNodedotjs,
    skillRows: [
      [
        { id: 'nodejs', label: 'Node.js', icon: SiNodedotjs },
        { id: 'express', label: 'Express.js', icon: SiExpress },
        { id: 'deno', label: 'Deno', icon: SiDeno },
        { id: 'hono', label: 'Hono', icon: SiHono },
        { id: 'aspnet-core', label: 'ASP.NET Core', icon: SiDotnet },
        { id: 'spring-boot', label: 'Spring Boot', icon: SiSpringboot },
        { id: 'spring-mvc', label: 'Spring MVC', icon: SiSpring },
        { id: 'spring-security', label: 'Spring Security', icon: FaUserShield },
        { id: 'restful-apis', label: 'RESTful APIs', icon: SiOpenapiinitiative },
        { id: 'rabbitmq', label: 'RabbitMQ', icon: SiRabbitmq },
      ],
    ],
  },
  {
    id: 'frontend-frameworks-ui',
    title: 'Frontend Frameworks & UI',
    icon: SiReact,
    skillRows: [
      [
        { id: 'react', label: 'React', icon: SiReact },
        { id: 'nextjs', label: 'Next.js', icon: SiNextdotjs },
        { id: 'angular', label: 'Angular', icon: SiAngular },
        { id: 'html', label: 'HTML', icon: SiHtml5 },
        { id: 'css', label: 'CSS', icon: SiCss },
        { id: 'tailwind-css', label: 'Tailwind CSS', icon: SiTailwindcss },
        { id: 'sass', label: 'Sass', icon: SiSass },
        { id: 'framer-motion', label: 'Framer Motion', icon: SiFramer },
      ],
    ],
  },
  {
    id: 'data-storage',
    title: 'Data & Storage',
    icon: FaDatabase,
    skillRows: [
      [
        { id: 'postgresql', label: 'PostgreSQL', icon: SiPostgresql },
        { id: 'mysql', label: 'MySQL', icon: SiMysql },
        { id: 'mongodb-atlas', label: 'MongoDB Atlas', icon: SiMongodb },
        { id: 'mongodb', label: 'MongoDB', icon: SiMongodb },
        { id: 'supabase', label: 'Supabase', icon: SiSupabase },
        { id: 'redis', label: 'Redis (Basics)', icon: SiRedis },
        { id: 'sql', label: 'SQL', icon: TbSql },
        { id: 'nosql', label: 'NoSQL', icon: SiMongodb },
      ],
    ],
  },
  {
    id: 'infrastructure-deployment',
    title: 'Infrastructure & Deployment',
    icon: SiDocker,
    skillRows: [
      [
        { id: 'docker', label: 'Docker', icon: SiDocker },
        { id: 'nginx', label: 'Nginx', icon: SiNginx },
        { id: 'git', label: 'Git', icon: SiGit },
        { id: 'github', label: 'GitHub', icon: SiGithub },
        { id: 'npm', label: 'NPM', icon: SiNpm },
        { id: 'github-actions', label: 'GitHub Actions', icon: SiGithubactions },
        { id: 'aws', label: 'AWS (EC2, S3, IAM)', icon: FaCloud },
        { id: 'google-cloud', label: 'Google Cloud (Compute Engine, Cloud Run, IAM)', icon: SiGooglecloud },
        { id: 'ci-cd', label: 'CI/CD', icon: FaDiagramProject },
        { id: 'deployment-pipelines', label: 'Deployment Pipelines', icon: FaDiagramProject },
      ],
    ],
  },
  {
    id: 'developer-tooling',
    title: 'Developer Tooling',
    icon: TbBrandVscode,
    skillRows: [
      [
        { id: 'vs-code', label: 'VS Code', icon: TbBrandVscode },
        { id: 'vscodium', label: 'VSCodium', icon: SiVscodium },
        { id: 'visual-studio', label: 'Visual Studio', icon: TbBrandVisualStudio },
        { id: 'intellij-idea', label: 'IntelliJ IDEA', icon: SiIntellijidea },
        { id: 'postman', label: 'Postman', icon: SiPostman },
        { id: 'openapi', label: 'OpenAPI (Swagger)', icon: SiOpenapiinitiative },
        { id: 'junit', label: 'JUnit', icon: SiJunit5 },
        { id: 'maven', label: 'Maven', icon: SiApachemaven },
        { id: 'ffmpeg', label: 'FFmpeg', icon: TbMathFunction },
      ],
    ],
  },
  {
    id: 'integrations-platforms',
    title: 'Integrations & Platforms',
    icon: SiRazorpay,
    skillRows: [
      [
        { id: 'razorpay', label: 'Razorpay', icon: SiRazorpay },
        { id: 'raspberry-pi', label: 'Raspberry Pi', icon: SiRaspberrypi },
        { id: 'r-studio', label: 'R Studio', icon: SiRstudioide },
        { id: 'matlab', label: 'Matlab', icon: TbMathFunction },
      ],
    ],
  },
]
