import { FaCode, FaDatabase } from 'react-icons/fa'
import {
  SiAngular,
  SiApachemaven,
  SiC,
  SiDeno,
  SiDocker,
  SiDotnet,
  SiExpress,
  SiFramer,
  SiGit,
  SiGithub,
  SiGnubash,
  SiHono,
  SiIntellijidea,
  SiJavascript,
  SiJunit5,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNpm,
  SiOpenjdk,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiR,
  SiRazorpay,
  SiReact,
  SiRstudioide,
  SiRust,
  SiSass,
  SiSpringboot,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVscodium,
} from 'react-icons/si'
import { TbBrandCSharp, TbBrandVisualStudio, TbBrandVscode, TbMathFunction, TbSql } from 'react-icons/tb'

import type { CapabilityCategory } from './types'

export const capabilityCategories: CapabilityCategory[] = [
  {
    id: 'programming-languages',
    title: 'Programming Languages',
    icon: FaCode,
    skillRows: [
      [
        { id: 'typescript', label: 'TypeScript', icon: SiTypescript },
        { id: 'javascript', label: 'JavaScript', icon: SiJavascript },
        { id: 'java', label: 'Java', icon: SiOpenjdk },
        { id: 'csharp', label: 'C#', icon: TbBrandCSharp },
        { id: 'rust', label: 'Rust', icon: SiRust },
        { id: 'python', label: 'Python', icon: SiPython },
      ],
      [
        { id: 'c', label: 'C', icon: SiC },
        { id: 'shell-script', label: 'Shell Script', icon: SiGnubash },
        { id: 'sql', label: 'SQL', icon: TbSql },
        { id: 'r', label: 'R', icon: SiR },
        { id: 'nosql', label: 'NoSQL', icon: SiMongodb },
      ],
    ],
  },
  {
    id: 'frameworks-libraries',
    title: 'Frameworks & Libraries',
    icon: SiReact,
    skillRows: [
      [
        { id: 'react', label: 'React', icon: SiReact },
        { id: 'nextjs', label: 'Next.js', icon: SiNextdotjs },
        { id: 'angular', label: 'Angular', icon: SiAngular },
        { id: 'nodejs', label: 'Node.js', icon: SiNodedotjs },
        { id: 'express', label: 'Express.js', icon: SiExpress },
        { id: 'deno', label: 'Deno', icon: SiDeno },
      ],
      [
        { id: 'hono', label: 'Hono', icon: SiHono },
        { id: 'aspnet-core', label: 'ASP.NET Core', icon: SiDotnet },
        { id: 'spring-boot', label: 'Spring Boot', icon: SiSpringboot },
        { id: 'tailwind-css', label: 'Tailwind CSS', icon: SiTailwindcss },
        { id: 'sass', label: 'Sass', icon: SiSass },
        { id: 'framer-motion', label: 'Framer Motion', icon: SiFramer },
      ],
    ],
  },
  {
    id: 'databases',
    title: 'Databases',
    icon: FaDatabase,
    skillRows: [
      [
        { id: 'postgresql', label: 'PostgreSQL', icon: SiPostgresql },
        { id: 'mysql', label: 'MySQL', icon: SiMysql },
        { id: 'mongodb', label: 'MongoDB', icon: SiMongodb },
        { id: 'supabase', label: 'Supabase', icon: SiSupabase },
      ],
    ],
  },
  {
    id: 'tools-platforms',
    title: 'Tools & Platforms',
    icon: SiGithub,
    skillRows: [
      [
        { id: 'git', label: 'Git', icon: SiGit },
        { id: 'github', label: 'GitHub', icon: SiGithub },
        { id: 'npm', label: 'npm', icon: SiNpm },
        { id: 'vs-code', label: 'VS Code', icon: TbBrandVscode },
        { id: 'vscodium', label: 'VSCodium', icon: SiVscodium },
        { id: 'visual-studio', label: 'Visual Studio', icon: TbBrandVisualStudio },
        { id: 'intellij-idea', label: 'IntelliJ IDEA', icon: SiIntellijidea },
        { id: 'maven', label: 'Maven', icon: SiApachemaven },
      ],
      [
        { id: 'junit', label: 'JUnit', icon: SiJunit5 },
        { id: 'postman', label: 'Postman', icon: SiPostman },
        { id: 'docker', label: 'Docker', icon: SiDocker },
        { id: 'nginx', label: 'Nginx', icon: SiNginx },
        { id: 'razorpay', label: 'Razorpay', icon: SiRazorpay },
        { id: 'rstudio', label: 'RStudio', icon: SiRstudioide },
        { id: 'matlab', label: 'MATLAB', icon: TbMathFunction },
      ],
    ],
  },
]
